// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/avraam311/calendar-service/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockeventService is a mock of eventService interface.
type MockeventService struct {
	ctrl     *gomock.Controller
	recorder *MockeventServiceMockRecorder
}

// MockeventServiceMockRecorder is the mock recorder for MockeventService.
type MockeventServiceMockRecorder struct {
	mock *MockeventService
}

// NewMockeventService creates a new mock instance.
func NewMockeventService(ctrl *gomock.Controller) *MockeventService {
	mock := &MockeventService{ctrl: ctrl}
	mock.recorder = &MockeventServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockeventService) EXPECT() *MockeventServiceMockRecorder {
	return m.recorder
}

// CreateEvent mocks base method.
func (m *MockeventService) CreateEvent(ctx context.Context, event *models.EventCreate) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEvent", ctx, event)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEvent indicates an expected call of CreateEvent.
func (mr *MockeventServiceMockRecorder) CreateEvent(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEvent", reflect.TypeOf((*MockeventService)(nil).CreateEvent), ctx, event)
}

// DeleteEvent mocks base method.
func (m *MockeventService) DeleteEvent(ctx context.Context, ID uint) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEvent", ctx, ID)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteEvent indicates an expected call of DeleteEvent.
func (mr *MockeventServiceMockRecorder) DeleteEvent(ctx, ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEvent", reflect.TypeOf((*MockeventService)(nil).DeleteEvent), ctx, ID)
}

// GetEvents mocks base method.
func (m *MockeventService) GetEvents(ctx context.Context, eventGet *models.EventGet) ([]*models.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvents", ctx, eventGet)
	ret0, _ := ret[0].([]*models.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvents indicates an expected call of GetEvents.
func (mr *MockeventServiceMockRecorder) GetEvents(ctx, eventGet interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvents", reflect.TypeOf((*MockeventService)(nil).GetEvents), ctx, eventGet)
}

// UpdateEvent mocks base method.
func (m *MockeventService) UpdateEvent(ctx context.Context, event *models.Event) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEvent", ctx, event)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEvent indicates an expected call of UpdateEvent.
func (mr *MockeventServiceMockRecorder) UpdateEvent(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEvent", reflect.TypeOf((*MockeventService)(nil).UpdateEvent), ctx, event)
}
